AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFront distribution that glues the separate
             services together into one website
Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: A name for the environment that this cloudformation will be part of.

Resources:

  # Describes what to cache and for how long
  ChatAppCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: 'chat-app-default'
        DefaultTTL: 0
        MaxTTL: 10
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Sec-WebSocket-Key
              - Sec-WebSocket-Version
              - Sec-WebSocket-Protocol
              - Sec-WebSocket-Accept
              - Sec-WebSocket-Extensions
          QueryStringsConfig:
            QueryStringBehavior: all

  # Describes the different origins and how to map incoming
  # traffic to different origin servers
  ChatAppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: 'index.html'
        Enabled: true
        Origins:
          - Id: 'web-static'
            DomainName:
              Fn::ImportValue:
                !Join [':', [!Ref 'EnvironmentName', 'WebEndpoint']]
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
              OriginKeepaliveTimeout: 60
          - Id: 'socket-app'
            DomainName:
              Fn::ImportValue:
                !Join [':', [!Ref 'EnvironmentName', 'ExternalDnsName']]
            CustomOriginConfig:
              OriginProtocolPolicy: 'http-only'
              OriginKeepaliveTimeout: 60
          - Id: 'search-gateway'
            DomainName:
              Fn::Join:
                - ''
                - - Fn::ImportValue: !Join [':', [!Ref 'EnvironmentName', 'ChatMessageSearchId']]
                  - '.execute-api.'
                  - !Ref "AWS::Region"
                  - .amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
              OriginKeepaliveTimeout: 60
        # Default behavior sends all static web traffic to the
        # AppRunner hosted endpoint
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachePolicyId: !Ref ChatAppCachePolicy
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: 'web-static'
          Compress: true
        CacheBehaviors:
          # Search traffic goes to API Gateway of the Lambda function
          - PathPattern: '/search*'
            TargetOriginId: 'search-gateway'
            CachePolicyId: !Ref ChatAppCachePolicy
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
          # Socket.io traffic goes to the Fargate hosted container
          - PathPattern: '/socket.io*'
            TargetOriginId: 'socket-app'
            CachePolicyId: !Ref ChatAppCachePolicy
            ViewerProtocolPolicy: redirect-to-https
            Compress: true

Outputs:
  PublicURL:
    Description: The name of the ECS cluster
    Value: !GetAtt ChatAppDistribution.DomainName
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'PublicURL' ] ]